var myString;
var myNum;
var myBool;
var myVar;
var strArr;
var numArr;
var boolArr;
myString = 'Hello'.slice(0, 3);
myNum = 1;
myBool = false;
myVar = true;
strArr = ['Hello', 'World'];
numArr = [0, 1, 1, 2, 3, 5, 8, 13, 21];
boolArr = [true, false, false, true, true, false];
console.log(myString);
console.log(myNum);
console.log(myBool);
console.log(myVar);
console.log(strArr);
console.log(numArr);
console.log(boolArr);
